version: 2

definitions:
  workspace: &workspace
    docker:
      # specify the version
      - image: circleci/golang:1.15

  job_presets: &job_presets
    build:
      <<: *workspace
      steps:
        - checkout
        - run:
           command: |
             PROTOC_ZIP=protoc-3.14.0-linux-x86_64.zip
             curl -OL https://github.com/google/protobuf/releases/download/v3.14.0/$PROTOC_ZIP
             sudo unzip -o $PROTOC_ZIP -d /usr/local/protoc
             sudo chmod +xr -R /usr/local/protoc
             sudo ln -s /usr/local/protoc/bin/protoc /usr/local/bin
             sudo ln -s /usr/local/protoc/include/google /usr/local/include/google
             go get -u github.com/golang/protobuf/protoc-gen-go
             curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.31.0/golangci-lint-1.31.0-linux-amd64.tar.gz | tar zx -C /tmp/
             sudo mv /tmp/golangci-lint-1.31.0-linux-amd64/golangci-lint /usr/local/bin
             sudo chmod +x /usr/local/bin/golangci-lint
        - run: make lint
        - run: make all tag=${CIRCLE_TAG}
        - persist_to_workspace:
           root: .
           paths:
             - ./*
    publish:
      <<: *workspace
      steps:
        - attach_workspace:
            at: .
        - run:
           command: |
             sudo apt-get install jq file
             sh ./misc/github-release.sh

jobs:
  <<: *job_presets

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
